export default {
	sections: [
		{
			label: 'Beliefs',
			description: 'How much do you agree with the following beliefs?',
			statements: [
				{ category: 'Emerald Enclave', label: 'The natural order must be respected and preserved.' },
				{ category: 'Emerald Enclave', label: 'Forces that upset the natural order must be destroyed.' },
				{ category: 'Emerald Enclave', label: 'Civilization and the wilderness must learn to coexist peacefully.' },
				{ category: 'Harpers', label: 'One can never have too much information or arcane knowledge.' },
				{ category: 'Harpers', label: 'Too much power leads to corruption. The abuse of magic must be closely monitored.' },
				{ category: 'Harpers', label: 'No one should be powerless.' },
				{ category: 'Lords\' Alliance', label: 'If civilization is to survive, all must unite against the dark forces that threaten it.' },
				{ category: 'Lords\' Alliance', label: 'Fight for your realm. Only you can bring honor, glory, and prosperity to your lord and homeland.' },
				{ category: 'Lords\' Alliance', label: 'Don\'t wait for the enemy to come to you. The best defense is a strong offense.' },
				{ category: 'Order of the Gauntlet', label: 'Faith is the greatest weapon against evil—faith in one\'s god, one\'s friends, and one\'s self.' },
				{ category: 'Order of the Gauntlet', label: 'Battling evil is an extraordinary task that requires extraordinary strength and bravery.' },
				{ category: 'Order of the Gauntlet', label: 'Punishing an evil act is just. Punishing an evil thought is not.' },
				{ category: 'Zhentarim', label: 'Your group is your family. You watch out for it, and it watches out for you.' },
				{ category: 'Zhentarim', label: 'You are the master of your own destiny. Never be less than what you deserve to be.' },
				{ category: 'Zhentarim', label: 'Everything—and everyone—has a price.' },
			],
		},
		{
			label: 'Goals',
			description: 'How much do you identify with the follow goals?',
			statements: [
				{ category: 'Emerald Enclave', label: 'Restore and preserve the natural order.' },
				{ category: 'Emerald Enclave', label: 'Destroy all that is unnatural.' },
				{ category: 'Emerald Enclave', label: 'Keep the elemental forces of the world in check.' },
				{ category: 'Emerald Enclave', label: 'Keep civilization and the wilderness from destroying each other.' },
				{ category: 'Harpers', label: 'Gather information throughout Faerûn.' },
				{ category: 'Harpers', label: 'Promote fairness and equality by covert means.' },
				{ category: 'Harpers', label: 'Thwart tyrants and leaders, governments, and organizations that grow too powerful.' },
				{ category: 'Harpers', label: 'Aid the weak, poor and oppressed.' },
				{ category: 'Lords\' Alliance', label: 'Ensure the safety and prosperity of cities and other settlements of Faerûn.' },
				{ category: 'Lords\' Alliance', label: 'Maintain a strong coalition against the forces of disorder.' },
				{ category: 'Lords\' Alliance', label: 'Proactively eliminate threats to the established powers.' },
				{ category: 'Lords\' Alliance', label: 'Bring honor and glory to one\'s leaders and one\'s homeland.' },
				{ category: 'Order of the Gauntlet', label: 'Be armed and vigilant against evil.' },
				{ category: 'Order of the Gauntlet', label: 'Identify evil threats such as secretive power groups and inherently evil creatures.' },
				{ category: 'Order of the Gauntlet', label: 'Enforce justice.' },
				{ category: 'Order of the Gauntlet', label: 'Enact retribution against evil actions—do not strike preemptively.' },
				{ category: 'Zhentarim', label: 'Amass wealth.' },
				{ category: 'Zhentarim', label: 'Look for opportunities to seize power.' },
				{ category: 'Zhentarim', label: 'Gain influence over important people and organizations.' },
				{ category: 'Zhentarim', label: 'Dominate Faerûn.' },
			],
		},
	],
};
